/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as OauthSilentCallbackRouteImport } from './routes/oauth.silent-callback'
import { Route as OauthLogoutCallbackRouteImport } from './routes/oauth.logout-callback'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedQueuesIndexRouteImport } from './routes/_authenticated/queues/index'
import { Route as AuthenticatedNodesIndexRouteImport } from './routes/_authenticated/nodes/index'
import { Route as AuthenticatedExchangesIndexRouteImport } from './routes/_authenticated/exchanges/index'
import { Route as AuthenticatedConnectionsIndexRouteImport } from './routes/_authenticated/connections/index'
import { Route as AuthenticatedChannelsIndexRouteImport } from './routes/_authenticated/channels/index'
import { Route as AuthenticatedNodesNameRouteImport } from './routes/_authenticated/nodes/$name'
import { Route as AuthenticatedConnectionsNameRouteImport } from './routes/_authenticated/connections/$name'
import { Route as AuthenticatedChannelsNameRouteImport } from './routes/_authenticated/channels/$name'
import { Route as AuthenticatedAdminLimitsRouteImport } from './routes/_authenticated/admin/limits'
import { Route as AuthenticatedAdminFeatureFlagsRouteImport } from './routes/_authenticated/admin/feature-flags'
import { Route as AuthenticatedAdminDeprecatedFeaturesRouteImport } from './routes/_authenticated/admin/deprecated-features'
import { Route as AuthenticatedAdminDefinitionsRouteImport } from './routes/_authenticated/admin/definitions'
import { Route as AuthenticatedAdminClusterRouteImport } from './routes/_authenticated/admin/cluster'
import { Route as AuthenticatedExtensionsTracingIndexRouteImport } from './routes/_authenticated/extensions/tracing/index'
import { Route as AuthenticatedExtensionsTopIndexRouteImport } from './routes/_authenticated/extensions/top/index'
import { Route as AuthenticatedAdminVhostsIndexRouteImport } from './routes/_authenticated/admin/vhosts/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminPoliciesIndexRouteImport } from './routes/_authenticated/admin/policies/index'
import { Route as AuthenticatedAdminLimitsIndexRouteImport } from './routes/_authenticated/admin/limits/index'
import { Route as AuthenticatedQueuesVhostNameRouteImport } from './routes/_authenticated/queues/$vhost.$name'
import { Route as AuthenticatedExtensionsTopEtsRouteImport } from './routes/_authenticated/extensions/top/ets'
import { Route as AuthenticatedExtensionsStreamsSuperStreamsRouteImport } from './routes/_authenticated/extensions/streams/super-streams'
import { Route as AuthenticatedExtensionsShovelsStatusRouteImport } from './routes/_authenticated/extensions/shovels/status'
import { Route as AuthenticatedExtensionsFederationStatusRouteImport } from './routes/_authenticated/extensions/federation/status'
import { Route as AuthenticatedExchangesVhostNameRouteImport } from './routes/_authenticated/exchanges/$vhost.$name'
import { Route as AuthenticatedAdminVhostsNameRouteImport } from './routes/_authenticated/admin/vhosts/$name'
import { Route as AuthenticatedAdminUsersNameRouteImport } from './routes/_authenticated/admin/users/$name'
import { Route as AuthenticatedExtensionsStreamsConnectionsIndexRouteImport } from './routes/_authenticated/extensions/streams/connections/index'
import { Route as AuthenticatedExtensionsShovelsManagementIndexRouteImport } from './routes/_authenticated/extensions/shovels/management/index'
import { Route as AuthenticatedExtensionsFederationUpstreamsIndexRouteImport } from './routes/_authenticated/extensions/federation/upstreams/index'
import { Route as AuthenticatedExtensionsTopProcessPidRouteImport } from './routes/_authenticated/extensions/top/process/$pid'
import { Route as AuthenticatedAdminPoliciesVhostNameRouteImport } from './routes/_authenticated/admin/policies/$vhost/$name'
import { Route as AuthenticatedExtensionsTracingNodeVhostNameRouteImport } from './routes/_authenticated/extensions/tracing/$node.$vhost.$name'
import { Route as AuthenticatedExtensionsStreamsConnectionsVhostNameRouteImport } from './routes/_authenticated/extensions/streams/connections/$vhost.$name'
import { Route as AuthenticatedExtensionsShovelsManagementVhostNameRouteImport } from './routes/_authenticated/extensions/shovels/management/$vhost.$name'
import { Route as AuthenticatedExtensionsFederationUpstreamsVhostNameRouteImport } from './routes/_authenticated/extensions/federation/upstreams/$vhost.$name'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OauthSilentCallbackRoute = OauthSilentCallbackRouteImport.update({
  id: '/oauth/silent-callback',
  path: '/oauth/silent-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLogoutCallbackRoute = OauthLogoutCallbackRouteImport.update({
  id: '/oauth/logout-callback',
  path: '/oauth/logout-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQueuesIndexRoute =
  AuthenticatedQueuesIndexRouteImport.update({
    id: '/queues/',
    path: '/queues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNodesIndexRoute = AuthenticatedNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExchangesIndexRoute =
  AuthenticatedExchangesIndexRouteImport.update({
    id: '/exchanges/',
    path: '/exchanges/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConnectionsIndexRoute =
  AuthenticatedConnectionsIndexRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChannelsIndexRoute =
  AuthenticatedChannelsIndexRouteImport.update({
    id: '/channels/',
    path: '/channels/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNodesNameRoute = AuthenticatedNodesNameRouteImport.update({
  id: '/nodes/$name',
  path: '/nodes/$name',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectionsNameRoute =
  AuthenticatedConnectionsNameRouteImport.update({
    id: '/connections/$name',
    path: '/connections/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChannelsNameRoute =
  AuthenticatedChannelsNameRouteImport.update({
    id: '/channels/$name',
    path: '/channels/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLimitsRoute =
  AuthenticatedAdminLimitsRouteImport.update({
    id: '/limits',
    path: '/limits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFeatureFlagsRoute =
  AuthenticatedAdminFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDeprecatedFeaturesRoute =
  AuthenticatedAdminDeprecatedFeaturesRouteImport.update({
    id: '/deprecated-features',
    path: '/deprecated-features',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDefinitionsRoute =
  AuthenticatedAdminDefinitionsRouteImport.update({
    id: '/definitions',
    path: '/definitions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClusterRoute =
  AuthenticatedAdminClusterRouteImport.update({
    id: '/cluster',
    path: '/cluster',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedExtensionsTracingIndexRoute =
  AuthenticatedExtensionsTracingIndexRouteImport.update({
    id: '/extensions/tracing/',
    path: '/extensions/tracing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsTopIndexRoute =
  AuthenticatedExtensionsTopIndexRouteImport.update({
    id: '/extensions/top/',
    path: '/extensions/top/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVhostsIndexRoute =
  AuthenticatedAdminVhostsIndexRouteImport.update({
    id: '/vhosts/',
    path: '/vhosts/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPoliciesIndexRoute =
  AuthenticatedAdminPoliciesIndexRouteImport.update({
    id: '/policies/',
    path: '/policies/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLimitsIndexRoute =
  AuthenticatedAdminLimitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminLimitsRoute,
  } as any)
const AuthenticatedQueuesVhostNameRoute =
  AuthenticatedQueuesVhostNameRouteImport.update({
    id: '/queues/$vhost/$name',
    path: '/queues/$vhost/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsTopEtsRoute =
  AuthenticatedExtensionsTopEtsRouteImport.update({
    id: '/extensions/top/ets',
    path: '/extensions/top/ets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsStreamsSuperStreamsRoute =
  AuthenticatedExtensionsStreamsSuperStreamsRouteImport.update({
    id: '/extensions/streams/super-streams',
    path: '/extensions/streams/super-streams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsShovelsStatusRoute =
  AuthenticatedExtensionsShovelsStatusRouteImport.update({
    id: '/extensions/shovels/status',
    path: '/extensions/shovels/status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsFederationStatusRoute =
  AuthenticatedExtensionsFederationStatusRouteImport.update({
    id: '/extensions/federation/status',
    path: '/extensions/federation/status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExchangesVhostNameRoute =
  AuthenticatedExchangesVhostNameRouteImport.update({
    id: '/exchanges/$vhost/$name',
    path: '/exchanges/$vhost/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVhostsNameRoute =
  AuthenticatedAdminVhostsNameRouteImport.update({
    id: '/vhosts/$name',
    path: '/vhosts/$name',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersNameRoute =
  AuthenticatedAdminUsersNameRouteImport.update({
    id: '/users/$name',
    path: '/users/$name',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedExtensionsStreamsConnectionsIndexRoute =
  AuthenticatedExtensionsStreamsConnectionsIndexRouteImport.update({
    id: '/extensions/streams/connections/',
    path: '/extensions/streams/connections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsShovelsManagementIndexRoute =
  AuthenticatedExtensionsShovelsManagementIndexRouteImport.update({
    id: '/extensions/shovels/management/',
    path: '/extensions/shovels/management/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsFederationUpstreamsIndexRoute =
  AuthenticatedExtensionsFederationUpstreamsIndexRouteImport.update({
    id: '/extensions/federation/upstreams/',
    path: '/extensions/federation/upstreams/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsTopProcessPidRoute =
  AuthenticatedExtensionsTopProcessPidRouteImport.update({
    id: '/extensions/top/process/$pid',
    path: '/extensions/top/process/$pid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPoliciesVhostNameRoute =
  AuthenticatedAdminPoliciesVhostNameRouteImport.update({
    id: '/policies/$vhost/$name',
    path: '/policies/$vhost/$name',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedExtensionsTracingNodeVhostNameRoute =
  AuthenticatedExtensionsTracingNodeVhostNameRouteImport.update({
    id: '/extensions/tracing/$node/$vhost/$name',
    path: '/extensions/tracing/$node/$vhost/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsStreamsConnectionsVhostNameRoute =
  AuthenticatedExtensionsStreamsConnectionsVhostNameRouteImport.update({
    id: '/extensions/streams/connections/$vhost/$name',
    path: '/extensions/streams/connections/$vhost/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsShovelsManagementVhostNameRoute =
  AuthenticatedExtensionsShovelsManagementVhostNameRouteImport.update({
    id: '/extensions/shovels/management/$vhost/$name',
    path: '/extensions/shovels/management/$vhost/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtensionsFederationUpstreamsVhostNameRoute =
  AuthenticatedExtensionsFederationUpstreamsVhostNameRouteImport.update({
    id: '/extensions/federation/upstreams/$vhost/$name',
    path: '/extensions/federation/upstreams/$vhost/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/logout-callback': typeof OauthLogoutCallbackRoute
  '/oauth/silent-callback': typeof OauthSilentCallbackRoute
  '/admin/cluster': typeof AuthenticatedAdminClusterRoute
  '/admin/definitions': typeof AuthenticatedAdminDefinitionsRoute
  '/admin/deprecated-features': typeof AuthenticatedAdminDeprecatedFeaturesRoute
  '/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/admin/limits': typeof AuthenticatedAdminLimitsRouteWithChildren
  '/channels/$name': typeof AuthenticatedChannelsNameRoute
  '/connections/$name': typeof AuthenticatedConnectionsNameRoute
  '/nodes/$name': typeof AuthenticatedNodesNameRoute
  '/channels/': typeof AuthenticatedChannelsIndexRoute
  '/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/exchanges/': typeof AuthenticatedExchangesIndexRoute
  '/nodes/': typeof AuthenticatedNodesIndexRoute
  '/queues/': typeof AuthenticatedQueuesIndexRoute
  '/admin/users/$name': typeof AuthenticatedAdminUsersNameRoute
  '/admin/vhosts/$name': typeof AuthenticatedAdminVhostsNameRoute
  '/exchanges/$vhost/$name': typeof AuthenticatedExchangesVhostNameRoute
  '/extensions/federation/status': typeof AuthenticatedExtensionsFederationStatusRoute
  '/extensions/shovels/status': typeof AuthenticatedExtensionsShovelsStatusRoute
  '/extensions/streams/super-streams': typeof AuthenticatedExtensionsStreamsSuperStreamsRoute
  '/extensions/top/ets': typeof AuthenticatedExtensionsTopEtsRoute
  '/queues/$vhost/$name': typeof AuthenticatedQueuesVhostNameRoute
  '/admin/limits/': typeof AuthenticatedAdminLimitsIndexRoute
  '/admin/policies/': typeof AuthenticatedAdminPoliciesIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/vhosts/': typeof AuthenticatedAdminVhostsIndexRoute
  '/extensions/top/': typeof AuthenticatedExtensionsTopIndexRoute
  '/extensions/tracing/': typeof AuthenticatedExtensionsTracingIndexRoute
  '/admin/policies/$vhost/$name': typeof AuthenticatedAdminPoliciesVhostNameRoute
  '/extensions/top/process/$pid': typeof AuthenticatedExtensionsTopProcessPidRoute
  '/extensions/federation/upstreams/': typeof AuthenticatedExtensionsFederationUpstreamsIndexRoute
  '/extensions/shovels/management/': typeof AuthenticatedExtensionsShovelsManagementIndexRoute
  '/extensions/streams/connections/': typeof AuthenticatedExtensionsStreamsConnectionsIndexRoute
  '/extensions/federation/upstreams/$vhost/$name': typeof AuthenticatedExtensionsFederationUpstreamsVhostNameRoute
  '/extensions/shovels/management/$vhost/$name': typeof AuthenticatedExtensionsShovelsManagementVhostNameRoute
  '/extensions/streams/connections/$vhost/$name': typeof AuthenticatedExtensionsStreamsConnectionsVhostNameRoute
  '/extensions/tracing/$node/$vhost/$name': typeof AuthenticatedExtensionsTracingNodeVhostNameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/logout-callback': typeof OauthLogoutCallbackRoute
  '/oauth/silent-callback': typeof OauthSilentCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/cluster': typeof AuthenticatedAdminClusterRoute
  '/admin/definitions': typeof AuthenticatedAdminDefinitionsRoute
  '/admin/deprecated-features': typeof AuthenticatedAdminDeprecatedFeaturesRoute
  '/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/channels/$name': typeof AuthenticatedChannelsNameRoute
  '/connections/$name': typeof AuthenticatedConnectionsNameRoute
  '/nodes/$name': typeof AuthenticatedNodesNameRoute
  '/channels': typeof AuthenticatedChannelsIndexRoute
  '/connections': typeof AuthenticatedConnectionsIndexRoute
  '/exchanges': typeof AuthenticatedExchangesIndexRoute
  '/nodes': typeof AuthenticatedNodesIndexRoute
  '/queues': typeof AuthenticatedQueuesIndexRoute
  '/admin/users/$name': typeof AuthenticatedAdminUsersNameRoute
  '/admin/vhosts/$name': typeof AuthenticatedAdminVhostsNameRoute
  '/exchanges/$vhost/$name': typeof AuthenticatedExchangesVhostNameRoute
  '/extensions/federation/status': typeof AuthenticatedExtensionsFederationStatusRoute
  '/extensions/shovels/status': typeof AuthenticatedExtensionsShovelsStatusRoute
  '/extensions/streams/super-streams': typeof AuthenticatedExtensionsStreamsSuperStreamsRoute
  '/extensions/top/ets': typeof AuthenticatedExtensionsTopEtsRoute
  '/queues/$vhost/$name': typeof AuthenticatedQueuesVhostNameRoute
  '/admin/limits': typeof AuthenticatedAdminLimitsIndexRoute
  '/admin/policies': typeof AuthenticatedAdminPoliciesIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/vhosts': typeof AuthenticatedAdminVhostsIndexRoute
  '/extensions/top': typeof AuthenticatedExtensionsTopIndexRoute
  '/extensions/tracing': typeof AuthenticatedExtensionsTracingIndexRoute
  '/admin/policies/$vhost/$name': typeof AuthenticatedAdminPoliciesVhostNameRoute
  '/extensions/top/process/$pid': typeof AuthenticatedExtensionsTopProcessPidRoute
  '/extensions/federation/upstreams': typeof AuthenticatedExtensionsFederationUpstreamsIndexRoute
  '/extensions/shovels/management': typeof AuthenticatedExtensionsShovelsManagementIndexRoute
  '/extensions/streams/connections': typeof AuthenticatedExtensionsStreamsConnectionsIndexRoute
  '/extensions/federation/upstreams/$vhost/$name': typeof AuthenticatedExtensionsFederationUpstreamsVhostNameRoute
  '/extensions/shovels/management/$vhost/$name': typeof AuthenticatedExtensionsShovelsManagementVhostNameRoute
  '/extensions/streams/connections/$vhost/$name': typeof AuthenticatedExtensionsStreamsConnectionsVhostNameRoute
  '/extensions/tracing/$node/$vhost/$name': typeof AuthenticatedExtensionsTracingNodeVhostNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/logout-callback': typeof OauthLogoutCallbackRoute
  '/oauth/silent-callback': typeof OauthSilentCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/cluster': typeof AuthenticatedAdminClusterRoute
  '/_authenticated/admin/definitions': typeof AuthenticatedAdminDefinitionsRoute
  '/_authenticated/admin/deprecated-features': typeof AuthenticatedAdminDeprecatedFeaturesRoute
  '/_authenticated/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/_authenticated/admin/limits': typeof AuthenticatedAdminLimitsRouteWithChildren
  '/_authenticated/channels/$name': typeof AuthenticatedChannelsNameRoute
  '/_authenticated/connections/$name': typeof AuthenticatedConnectionsNameRoute
  '/_authenticated/nodes/$name': typeof AuthenticatedNodesNameRoute
  '/_authenticated/channels/': typeof AuthenticatedChannelsIndexRoute
  '/_authenticated/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/_authenticated/exchanges/': typeof AuthenticatedExchangesIndexRoute
  '/_authenticated/nodes/': typeof AuthenticatedNodesIndexRoute
  '/_authenticated/queues/': typeof AuthenticatedQueuesIndexRoute
  '/_authenticated/admin/users/$name': typeof AuthenticatedAdminUsersNameRoute
  '/_authenticated/admin/vhosts/$name': typeof AuthenticatedAdminVhostsNameRoute
  '/_authenticated/exchanges/$vhost/$name': typeof AuthenticatedExchangesVhostNameRoute
  '/_authenticated/extensions/federation/status': typeof AuthenticatedExtensionsFederationStatusRoute
  '/_authenticated/extensions/shovels/status': typeof AuthenticatedExtensionsShovelsStatusRoute
  '/_authenticated/extensions/streams/super-streams': typeof AuthenticatedExtensionsStreamsSuperStreamsRoute
  '/_authenticated/extensions/top/ets': typeof AuthenticatedExtensionsTopEtsRoute
  '/_authenticated/queues/$vhost/$name': typeof AuthenticatedQueuesVhostNameRoute
  '/_authenticated/admin/limits/': typeof AuthenticatedAdminLimitsIndexRoute
  '/_authenticated/admin/policies/': typeof AuthenticatedAdminPoliciesIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/admin/vhosts/': typeof AuthenticatedAdminVhostsIndexRoute
  '/_authenticated/extensions/top/': typeof AuthenticatedExtensionsTopIndexRoute
  '/_authenticated/extensions/tracing/': typeof AuthenticatedExtensionsTracingIndexRoute
  '/_authenticated/admin/policies/$vhost/$name': typeof AuthenticatedAdminPoliciesVhostNameRoute
  '/_authenticated/extensions/top/process/$pid': typeof AuthenticatedExtensionsTopProcessPidRoute
  '/_authenticated/extensions/federation/upstreams/': typeof AuthenticatedExtensionsFederationUpstreamsIndexRoute
  '/_authenticated/extensions/shovels/management/': typeof AuthenticatedExtensionsShovelsManagementIndexRoute
  '/_authenticated/extensions/streams/connections/': typeof AuthenticatedExtensionsStreamsConnectionsIndexRoute
  '/_authenticated/extensions/federation/upstreams/$vhost/$name': typeof AuthenticatedExtensionsFederationUpstreamsVhostNameRoute
  '/_authenticated/extensions/shovels/management/$vhost/$name': typeof AuthenticatedExtensionsShovelsManagementVhostNameRoute
  '/_authenticated/extensions/streams/connections/$vhost/$name': typeof AuthenticatedExtensionsStreamsConnectionsVhostNameRoute
  '/_authenticated/extensions/tracing/$node/$vhost/$name': typeof AuthenticatedExtensionsTracingNodeVhostNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/oauth/callback'
    | '/oauth/logout-callback'
    | '/oauth/silent-callback'
    | '/admin/cluster'
    | '/admin/definitions'
    | '/admin/deprecated-features'
    | '/admin/feature-flags'
    | '/admin/limits'
    | '/channels/$name'
    | '/connections/$name'
    | '/nodes/$name'
    | '/channels/'
    | '/connections/'
    | '/exchanges/'
    | '/nodes/'
    | '/queues/'
    | '/admin/users/$name'
    | '/admin/vhosts/$name'
    | '/exchanges/$vhost/$name'
    | '/extensions/federation/status'
    | '/extensions/shovels/status'
    | '/extensions/streams/super-streams'
    | '/extensions/top/ets'
    | '/queues/$vhost/$name'
    | '/admin/limits/'
    | '/admin/policies/'
    | '/admin/users/'
    | '/admin/vhosts/'
    | '/extensions/top/'
    | '/extensions/tracing/'
    | '/admin/policies/$vhost/$name'
    | '/extensions/top/process/$pid'
    | '/extensions/federation/upstreams/'
    | '/extensions/shovels/management/'
    | '/extensions/streams/connections/'
    | '/extensions/federation/upstreams/$vhost/$name'
    | '/extensions/shovels/management/$vhost/$name'
    | '/extensions/streams/connections/$vhost/$name'
    | '/extensions/tracing/$node/$vhost/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/oauth/callback'
    | '/oauth/logout-callback'
    | '/oauth/silent-callback'
    | '/'
    | '/admin/cluster'
    | '/admin/definitions'
    | '/admin/deprecated-features'
    | '/admin/feature-flags'
    | '/channels/$name'
    | '/connections/$name'
    | '/nodes/$name'
    | '/channels'
    | '/connections'
    | '/exchanges'
    | '/nodes'
    | '/queues'
    | '/admin/users/$name'
    | '/admin/vhosts/$name'
    | '/exchanges/$vhost/$name'
    | '/extensions/federation/status'
    | '/extensions/shovels/status'
    | '/extensions/streams/super-streams'
    | '/extensions/top/ets'
    | '/queues/$vhost/$name'
    | '/admin/limits'
    | '/admin/policies'
    | '/admin/users'
    | '/admin/vhosts'
    | '/extensions/top'
    | '/extensions/tracing'
    | '/admin/policies/$vhost/$name'
    | '/extensions/top/process/$pid'
    | '/extensions/federation/upstreams'
    | '/extensions/shovels/management'
    | '/extensions/streams/connections'
    | '/extensions/federation/upstreams/$vhost/$name'
    | '/extensions/shovels/management/$vhost/$name'
    | '/extensions/streams/connections/$vhost/$name'
    | '/extensions/tracing/$node/$vhost/$name'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/oauth/callback'
    | '/oauth/logout-callback'
    | '/oauth/silent-callback'
    | '/_authenticated/'
    | '/_authenticated/admin/cluster'
    | '/_authenticated/admin/definitions'
    | '/_authenticated/admin/deprecated-features'
    | '/_authenticated/admin/feature-flags'
    | '/_authenticated/admin/limits'
    | '/_authenticated/channels/$name'
    | '/_authenticated/connections/$name'
    | '/_authenticated/nodes/$name'
    | '/_authenticated/channels/'
    | '/_authenticated/connections/'
    | '/_authenticated/exchanges/'
    | '/_authenticated/nodes/'
    | '/_authenticated/queues/'
    | '/_authenticated/admin/users/$name'
    | '/_authenticated/admin/vhosts/$name'
    | '/_authenticated/exchanges/$vhost/$name'
    | '/_authenticated/extensions/federation/status'
    | '/_authenticated/extensions/shovels/status'
    | '/_authenticated/extensions/streams/super-streams'
    | '/_authenticated/extensions/top/ets'
    | '/_authenticated/queues/$vhost/$name'
    | '/_authenticated/admin/limits/'
    | '/_authenticated/admin/policies/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/admin/vhosts/'
    | '/_authenticated/extensions/top/'
    | '/_authenticated/extensions/tracing/'
    | '/_authenticated/admin/policies/$vhost/$name'
    | '/_authenticated/extensions/top/process/$pid'
    | '/_authenticated/extensions/federation/upstreams/'
    | '/_authenticated/extensions/shovels/management/'
    | '/_authenticated/extensions/streams/connections/'
    | '/_authenticated/extensions/federation/upstreams/$vhost/$name'
    | '/_authenticated/extensions/shovels/management/$vhost/$name'
    | '/_authenticated/extensions/streams/connections/$vhost/$name'
    | '/_authenticated/extensions/tracing/$node/$vhost/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthLogoutCallbackRoute: typeof OauthLogoutCallbackRoute
  OauthSilentCallbackRoute: typeof OauthSilentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/oauth/silent-callback': {
      id: '/oauth/silent-callback'
      path: '/oauth/silent-callback'
      fullPath: '/oauth/silent-callback'
      preLoaderRoute: typeof OauthSilentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/logout-callback': {
      id: '/oauth/logout-callback'
      path: '/oauth/logout-callback'
      fullPath: '/oauth/logout-callback'
      preLoaderRoute: typeof OauthLogoutCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queues/': {
      id: '/_authenticated/queues/'
      path: '/queues'
      fullPath: '/queues/'
      preLoaderRoute: typeof AuthenticatedQueuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nodes/': {
      id: '/_authenticated/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AuthenticatedNodesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exchanges/': {
      id: '/_authenticated/exchanges/'
      path: '/exchanges'
      fullPath: '/exchanges/'
      preLoaderRoute: typeof AuthenticatedExchangesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections/': {
      id: '/_authenticated/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthenticatedConnectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels/': {
      id: '/_authenticated/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthenticatedChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nodes/$name': {
      id: '/_authenticated/nodes/$name'
      path: '/nodes/$name'
      fullPath: '/nodes/$name'
      preLoaderRoute: typeof AuthenticatedNodesNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections/$name': {
      id: '/_authenticated/connections/$name'
      path: '/connections/$name'
      fullPath: '/connections/$name'
      preLoaderRoute: typeof AuthenticatedConnectionsNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels/$name': {
      id: '/_authenticated/channels/$name'
      path: '/channels/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof AuthenticatedChannelsNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/limits': {
      id: '/_authenticated/admin/limits'
      path: '/limits'
      fullPath: '/admin/limits'
      preLoaderRoute: typeof AuthenticatedAdminLimitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/feature-flags': {
      id: '/_authenticated/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AuthenticatedAdminFeatureFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/deprecated-features': {
      id: '/_authenticated/admin/deprecated-features'
      path: '/deprecated-features'
      fullPath: '/admin/deprecated-features'
      preLoaderRoute: typeof AuthenticatedAdminDeprecatedFeaturesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/definitions': {
      id: '/_authenticated/admin/definitions'
      path: '/definitions'
      fullPath: '/admin/definitions'
      preLoaderRoute: typeof AuthenticatedAdminDefinitionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cluster': {
      id: '/_authenticated/admin/cluster'
      path: '/cluster'
      fullPath: '/admin/cluster'
      preLoaderRoute: typeof AuthenticatedAdminClusterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/extensions/tracing/': {
      id: '/_authenticated/extensions/tracing/'
      path: '/extensions/tracing'
      fullPath: '/extensions/tracing/'
      preLoaderRoute: typeof AuthenticatedExtensionsTracingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/top/': {
      id: '/_authenticated/extensions/top/'
      path: '/extensions/top'
      fullPath: '/extensions/top/'
      preLoaderRoute: typeof AuthenticatedExtensionsTopIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/vhosts/': {
      id: '/_authenticated/admin/vhosts/'
      path: '/vhosts'
      fullPath: '/admin/vhosts/'
      preLoaderRoute: typeof AuthenticatedAdminVhostsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/policies/': {
      id: '/_authenticated/admin/policies/'
      path: '/policies'
      fullPath: '/admin/policies/'
      preLoaderRoute: typeof AuthenticatedAdminPoliciesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/limits/': {
      id: '/_authenticated/admin/limits/'
      path: '/'
      fullPath: '/admin/limits/'
      preLoaderRoute: typeof AuthenticatedAdminLimitsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminLimitsRoute
    }
    '/_authenticated/queues/$vhost/$name': {
      id: '/_authenticated/queues/$vhost/$name'
      path: '/queues/$vhost/$name'
      fullPath: '/queues/$vhost/$name'
      preLoaderRoute: typeof AuthenticatedQueuesVhostNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/top/ets': {
      id: '/_authenticated/extensions/top/ets'
      path: '/extensions/top/ets'
      fullPath: '/extensions/top/ets'
      preLoaderRoute: typeof AuthenticatedExtensionsTopEtsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/streams/super-streams': {
      id: '/_authenticated/extensions/streams/super-streams'
      path: '/extensions/streams/super-streams'
      fullPath: '/extensions/streams/super-streams'
      preLoaderRoute: typeof AuthenticatedExtensionsStreamsSuperStreamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/shovels/status': {
      id: '/_authenticated/extensions/shovels/status'
      path: '/extensions/shovels/status'
      fullPath: '/extensions/shovels/status'
      preLoaderRoute: typeof AuthenticatedExtensionsShovelsStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/federation/status': {
      id: '/_authenticated/extensions/federation/status'
      path: '/extensions/federation/status'
      fullPath: '/extensions/federation/status'
      preLoaderRoute: typeof AuthenticatedExtensionsFederationStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exchanges/$vhost/$name': {
      id: '/_authenticated/exchanges/$vhost/$name'
      path: '/exchanges/$vhost/$name'
      fullPath: '/exchanges/$vhost/$name'
      preLoaderRoute: typeof AuthenticatedExchangesVhostNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/vhosts/$name': {
      id: '/_authenticated/admin/vhosts/$name'
      path: '/vhosts/$name'
      fullPath: '/admin/vhosts/$name'
      preLoaderRoute: typeof AuthenticatedAdminVhostsNameRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/$name': {
      id: '/_authenticated/admin/users/$name'
      path: '/users/$name'
      fullPath: '/admin/users/$name'
      preLoaderRoute: typeof AuthenticatedAdminUsersNameRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/extensions/streams/connections/': {
      id: '/_authenticated/extensions/streams/connections/'
      path: '/extensions/streams/connections'
      fullPath: '/extensions/streams/connections/'
      preLoaderRoute: typeof AuthenticatedExtensionsStreamsConnectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/shovels/management/': {
      id: '/_authenticated/extensions/shovels/management/'
      path: '/extensions/shovels/management'
      fullPath: '/extensions/shovels/management/'
      preLoaderRoute: typeof AuthenticatedExtensionsShovelsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/federation/upstreams/': {
      id: '/_authenticated/extensions/federation/upstreams/'
      path: '/extensions/federation/upstreams'
      fullPath: '/extensions/federation/upstreams/'
      preLoaderRoute: typeof AuthenticatedExtensionsFederationUpstreamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/top/process/$pid': {
      id: '/_authenticated/extensions/top/process/$pid'
      path: '/extensions/top/process/$pid'
      fullPath: '/extensions/top/process/$pid'
      preLoaderRoute: typeof AuthenticatedExtensionsTopProcessPidRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/policies/$vhost/$name': {
      id: '/_authenticated/admin/policies/$vhost/$name'
      path: '/policies/$vhost/$name'
      fullPath: '/admin/policies/$vhost/$name'
      preLoaderRoute: typeof AuthenticatedAdminPoliciesVhostNameRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/extensions/tracing/$node/$vhost/$name': {
      id: '/_authenticated/extensions/tracing/$node/$vhost/$name'
      path: '/extensions/tracing/$node/$vhost/$name'
      fullPath: '/extensions/tracing/$node/$vhost/$name'
      preLoaderRoute: typeof AuthenticatedExtensionsTracingNodeVhostNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/streams/connections/$vhost/$name': {
      id: '/_authenticated/extensions/streams/connections/$vhost/$name'
      path: '/extensions/streams/connections/$vhost/$name'
      fullPath: '/extensions/streams/connections/$vhost/$name'
      preLoaderRoute: typeof AuthenticatedExtensionsStreamsConnectionsVhostNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/shovels/management/$vhost/$name': {
      id: '/_authenticated/extensions/shovels/management/$vhost/$name'
      path: '/extensions/shovels/management/$vhost/$name'
      fullPath: '/extensions/shovels/management/$vhost/$name'
      preLoaderRoute: typeof AuthenticatedExtensionsShovelsManagementVhostNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extensions/federation/upstreams/$vhost/$name': {
      id: '/_authenticated/extensions/federation/upstreams/$vhost/$name'
      path: '/extensions/federation/upstreams/$vhost/$name'
      fullPath: '/extensions/federation/upstreams/$vhost/$name'
      preLoaderRoute: typeof AuthenticatedExtensionsFederationUpstreamsVhostNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminLimitsRouteChildren {
  AuthenticatedAdminLimitsIndexRoute: typeof AuthenticatedAdminLimitsIndexRoute
}

const AuthenticatedAdminLimitsRouteChildren: AuthenticatedAdminLimitsRouteChildren =
  {
    AuthenticatedAdminLimitsIndexRoute: AuthenticatedAdminLimitsIndexRoute,
  }

const AuthenticatedAdminLimitsRouteWithChildren =
  AuthenticatedAdminLimitsRoute._addFileChildren(
    AuthenticatedAdminLimitsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminClusterRoute: typeof AuthenticatedAdminClusterRoute
  AuthenticatedAdminDefinitionsRoute: typeof AuthenticatedAdminDefinitionsRoute
  AuthenticatedAdminDeprecatedFeaturesRoute: typeof AuthenticatedAdminDeprecatedFeaturesRoute
  AuthenticatedAdminFeatureFlagsRoute: typeof AuthenticatedAdminFeatureFlagsRoute
  AuthenticatedAdminLimitsRoute: typeof AuthenticatedAdminLimitsRouteWithChildren
  AuthenticatedAdminUsersNameRoute: typeof AuthenticatedAdminUsersNameRoute
  AuthenticatedAdminVhostsNameRoute: typeof AuthenticatedAdminVhostsNameRoute
  AuthenticatedAdminPoliciesIndexRoute: typeof AuthenticatedAdminPoliciesIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminVhostsIndexRoute: typeof AuthenticatedAdminVhostsIndexRoute
  AuthenticatedAdminPoliciesVhostNameRoute: typeof AuthenticatedAdminPoliciesVhostNameRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminClusterRoute: AuthenticatedAdminClusterRoute,
    AuthenticatedAdminDefinitionsRoute: AuthenticatedAdminDefinitionsRoute,
    AuthenticatedAdminDeprecatedFeaturesRoute:
      AuthenticatedAdminDeprecatedFeaturesRoute,
    AuthenticatedAdminFeatureFlagsRoute: AuthenticatedAdminFeatureFlagsRoute,
    AuthenticatedAdminLimitsRoute: AuthenticatedAdminLimitsRouteWithChildren,
    AuthenticatedAdminUsersNameRoute: AuthenticatedAdminUsersNameRoute,
    AuthenticatedAdminVhostsNameRoute: AuthenticatedAdminVhostsNameRoute,
    AuthenticatedAdminPoliciesIndexRoute: AuthenticatedAdminPoliciesIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
    AuthenticatedAdminVhostsIndexRoute: AuthenticatedAdminVhostsIndexRoute,
    AuthenticatedAdminPoliciesVhostNameRoute:
      AuthenticatedAdminPoliciesVhostNameRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChannelsNameRoute: typeof AuthenticatedChannelsNameRoute
  AuthenticatedConnectionsNameRoute: typeof AuthenticatedConnectionsNameRoute
  AuthenticatedNodesNameRoute: typeof AuthenticatedNodesNameRoute
  AuthenticatedChannelsIndexRoute: typeof AuthenticatedChannelsIndexRoute
  AuthenticatedConnectionsIndexRoute: typeof AuthenticatedConnectionsIndexRoute
  AuthenticatedExchangesIndexRoute: typeof AuthenticatedExchangesIndexRoute
  AuthenticatedNodesIndexRoute: typeof AuthenticatedNodesIndexRoute
  AuthenticatedQueuesIndexRoute: typeof AuthenticatedQueuesIndexRoute
  AuthenticatedExchangesVhostNameRoute: typeof AuthenticatedExchangesVhostNameRoute
  AuthenticatedExtensionsFederationStatusRoute: typeof AuthenticatedExtensionsFederationStatusRoute
  AuthenticatedExtensionsShovelsStatusRoute: typeof AuthenticatedExtensionsShovelsStatusRoute
  AuthenticatedExtensionsStreamsSuperStreamsRoute: typeof AuthenticatedExtensionsStreamsSuperStreamsRoute
  AuthenticatedExtensionsTopEtsRoute: typeof AuthenticatedExtensionsTopEtsRoute
  AuthenticatedQueuesVhostNameRoute: typeof AuthenticatedQueuesVhostNameRoute
  AuthenticatedExtensionsTopIndexRoute: typeof AuthenticatedExtensionsTopIndexRoute
  AuthenticatedExtensionsTracingIndexRoute: typeof AuthenticatedExtensionsTracingIndexRoute
  AuthenticatedExtensionsTopProcessPidRoute: typeof AuthenticatedExtensionsTopProcessPidRoute
  AuthenticatedExtensionsFederationUpstreamsIndexRoute: typeof AuthenticatedExtensionsFederationUpstreamsIndexRoute
  AuthenticatedExtensionsShovelsManagementIndexRoute: typeof AuthenticatedExtensionsShovelsManagementIndexRoute
  AuthenticatedExtensionsStreamsConnectionsIndexRoute: typeof AuthenticatedExtensionsStreamsConnectionsIndexRoute
  AuthenticatedExtensionsFederationUpstreamsVhostNameRoute: typeof AuthenticatedExtensionsFederationUpstreamsVhostNameRoute
  AuthenticatedExtensionsShovelsManagementVhostNameRoute: typeof AuthenticatedExtensionsShovelsManagementVhostNameRoute
  AuthenticatedExtensionsStreamsConnectionsVhostNameRoute: typeof AuthenticatedExtensionsStreamsConnectionsVhostNameRoute
  AuthenticatedExtensionsTracingNodeVhostNameRoute: typeof AuthenticatedExtensionsTracingNodeVhostNameRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChannelsNameRoute: AuthenticatedChannelsNameRoute,
  AuthenticatedConnectionsNameRoute: AuthenticatedConnectionsNameRoute,
  AuthenticatedNodesNameRoute: AuthenticatedNodesNameRoute,
  AuthenticatedChannelsIndexRoute: AuthenticatedChannelsIndexRoute,
  AuthenticatedConnectionsIndexRoute: AuthenticatedConnectionsIndexRoute,
  AuthenticatedExchangesIndexRoute: AuthenticatedExchangesIndexRoute,
  AuthenticatedNodesIndexRoute: AuthenticatedNodesIndexRoute,
  AuthenticatedQueuesIndexRoute: AuthenticatedQueuesIndexRoute,
  AuthenticatedExchangesVhostNameRoute: AuthenticatedExchangesVhostNameRoute,
  AuthenticatedExtensionsFederationStatusRoute:
    AuthenticatedExtensionsFederationStatusRoute,
  AuthenticatedExtensionsShovelsStatusRoute:
    AuthenticatedExtensionsShovelsStatusRoute,
  AuthenticatedExtensionsStreamsSuperStreamsRoute:
    AuthenticatedExtensionsStreamsSuperStreamsRoute,
  AuthenticatedExtensionsTopEtsRoute: AuthenticatedExtensionsTopEtsRoute,
  AuthenticatedQueuesVhostNameRoute: AuthenticatedQueuesVhostNameRoute,
  AuthenticatedExtensionsTopIndexRoute: AuthenticatedExtensionsTopIndexRoute,
  AuthenticatedExtensionsTracingIndexRoute:
    AuthenticatedExtensionsTracingIndexRoute,
  AuthenticatedExtensionsTopProcessPidRoute:
    AuthenticatedExtensionsTopProcessPidRoute,
  AuthenticatedExtensionsFederationUpstreamsIndexRoute:
    AuthenticatedExtensionsFederationUpstreamsIndexRoute,
  AuthenticatedExtensionsShovelsManagementIndexRoute:
    AuthenticatedExtensionsShovelsManagementIndexRoute,
  AuthenticatedExtensionsStreamsConnectionsIndexRoute:
    AuthenticatedExtensionsStreamsConnectionsIndexRoute,
  AuthenticatedExtensionsFederationUpstreamsVhostNameRoute:
    AuthenticatedExtensionsFederationUpstreamsVhostNameRoute,
  AuthenticatedExtensionsShovelsManagementVhostNameRoute:
    AuthenticatedExtensionsShovelsManagementVhostNameRoute,
  AuthenticatedExtensionsStreamsConnectionsVhostNameRoute:
    AuthenticatedExtensionsStreamsConnectionsVhostNameRoute,
  AuthenticatedExtensionsTracingNodeVhostNameRoute:
    AuthenticatedExtensionsTracingNodeVhostNameRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthLogoutCallbackRoute: OauthLogoutCallbackRoute,
  OauthSilentCallbackRoute: OauthSilentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
